name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13] # 定义多个 Python 版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Python ${{ matrix.python-version }}
        run: |
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            -t ${{ secrets.DOCKER_USERNAME }}/git-python:${{ matrix.python-version }} .

      - name: Push Docker image for Python ${{ matrix.python-version }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/git-python:${{ matrix.python-version }}

      - name: Tag and Push latest
        if: matrix.python-version == '3.13'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/git-python:3.13 ${{ secrets.DOCKER_USERNAME }}/git-python:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/git-python:latest